"""Initial migration

Revision ID: 953a1e91bb41
Revises:
Create Date: 2025-03-11 14:44:19.445937

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '953a1e91bb41'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'fastapi_comments',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('task_id', sa.String(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('content', sa.String(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_fastapi_comments_id'), 'fastapi_comments', ['id'], unique=False
    )
    op.create_index(
        op.f('ix_fastapi_comments_task_id'),
        'fastapi_comments',
        ['task_id'],
        unique=False,
    )
    op.create_index(
        op.f('ix_fastapi_comments_user_id'),
        'fastapi_comments',
        ['user_id'],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fastapi_comments_user_id'), table_name='fastapi_comments')
    op.drop_index(op.f('ix_fastapi_comments_task_id'), table_name='fastapi_comments')
    op.drop_index(op.f('ix_fastapi_comments_id'), table_name='fastapi_comments')
    op.drop_table('fastapi_comments')
    # ### end Alembic commands ###
