networks:
  todo_network:
    driver: bridge

services:
  commentsapi:
    build:
      context: ../..
      dockerfile: infra/docker/Dockerfile
    entrypoint: infra/api/entrypoint.sh
    volumes:
      - ../..:/comments_api
      - ../db/wait-for-it.sh:/todo_api/infra/db/wait-for-it.sh
      - ../api/supervisord.conf:/etc/supervisord.conf
    ports:
      - "8090:8090"
    depends_on:
      - comments_db
      - comments_redis
    env_file:
      - ../api/comments_api.env
    networks:
      - todo_network

  comments_db:
    image: postgres:13
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../db/init.sh:/docker-entrypoint-initdb.d/init.sh
    ports:
      - "5434:5432"
    env_file:
      - ../db/db.env
    networks:
      - todo_network

  comments_redis:
    image: redis:alpine
    ports:
      - "6381:6379"
    volumes:
      - redis_data:/data
    networks:
      - todo_network

volumes:
  postgres_data:
  redis_data:
